development:
  adapter: postgresql
  encoding: unicode
  database: chemotion_dev
  pool: 5
  username: postgres
  password:
  template: template0
  host: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: chemotion_test
  pool: 5
  username: postgres
  password:
  template: template0
  host: postgres
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: chemotion_eln_prod
  pool: 5
  username: chemotion_eln_prod
  password: vG23C6GjUtA=
